- name: install redis
  ansible.builtin.dnf:
   name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm 
   state: present
   disable_gpg_check: true

- name: enable
  ansible.builtin.command: dnf module enable redis:remi-6.2 -y

- name: install redis
  ansible.builtin.dnf:
   name: redis
   state: present

- name: allow remote connections
  ansible.builtin.replace:
   path: /etc/redis.conf
   regexp: 127.0.0.1
   replace: 0.0.0.0

- name: start and enable redis
  ansible.builtin.service:
   name: redis
   enabled: yes
   state: started




