- name: copy mongodb repo
  ansible.builtin.copy:
   src: mongo.repo
   dest: /etc/yum.repos.d/mongo.repo
   


- name: import roles
  ansible.builtin.import_role:
   name: common
   tasks_from: appsetup


- name: replace config
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: 127.0.0.1
   replace: 0.0.0.0

- name: restart the server
  ansible.builtin.service:
   name: mongod
   state: restarted