- name: copy mongodb repo
  ansible.builtin.import_role:
   name: common
   tasks_from: appsetup

- name: copy mongo repo
  ansible.builtin.template:
   src: mongo.repo.j2
   dest: /etc/yum.repos.d/mongo.repo

- name: replace config
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: 127.0.0.1
   replace: 0.0.0.0

- name: restart the server
  ansible.builtin.service:
   name: mongod
   state: restarted