- name: copy mongo repo
  ansible.builtin.template:
   src: mongo.repo.j2
   dest: /etc/yum.repos.d/mongo.repo
   remote_src: yes

- name: install mongodb-org
  ansible.builtin.dnf:
   name: mongodb-org
   state: present

- name : start and enable mongodb
  ansible.builtin.service:
   name: mongodb-org
   enabled: yes
   state: started